name: test_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  lazy_load_indexed_stack: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  freezed: ^2.4.6
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  connectivity_plus: ^5.0.2
  json_annotation: ^4.8.1
  either_dart: ^1.0.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.4
  shared_preferences: ^2.2.2
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
