name: test_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  get: ^4.6.6
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.0+4
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  lazy_load_indexed_stack: ^1.1.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
