import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:test_app/feature/home/model/movie_model.dart';
import 'package:test_app/feature/home/repository/movie_repository.dart';
import 'package:test_app/feature/home/state/home_state.dart';
import 'package:test_app/feature/home/widget/entity/home_entity.dart';
import 'package:test_app/feature/home/widget/entity/movie_entity.dart';
import 'package:test_app/shared/app_enum.dart';

part 'home_provider.g.dart';

//Generated by @riverpod
// final homeNotifierProvider =
//     NotifierProvider<HomeNotifier, HomeState>(HomeNotifier.new);

@riverpod
class HomeNotifier extends _$HomeNotifier {
  late final movieRepo = ref.read(movieRepoProvider);
  @override
  HomeState build() {
    return HomeState(mapState: {
      for (var key in MovieType.values) key: HomeEntity(movies: [])
    });
  }

  Future reloadPage(MovieType type) async {
    Map<MovieType, HomeEntity> data = Map.from(state.mapState);
    var result = await movieRepo.callMovieByType(type);

    result.when(
        loading: () {},
        movieLoaded: (response) {
          data[type]?.movies = toListMovieEntity(response);
          data[type]?.isLoading = false;
          state = state.copyWith(mapState: data);
        },
        error: (e) {});
  }

  Future getNewPage(MovieType type) async {
    Map<MovieType, HomeEntity> data = Map.from(state.mapState);
    var result = await movieRepo.callMovieByType(type,
        page: 1 + (data[type]!.movies.length / 20).floor());

    result.when(
        loading: () {},
        movieLoaded: (response) {
          data[type]?.movies.addAll(toListMovieEntity(response));
          state = state.copyWith(mapState: data);
        },
        error: (e) {});
  }

  List<MovieEntity> toListMovieEntity(MovieResponse movie) {
    var list = movie.results ?? [];
    return list
        .map((e) => MovieEntity(
            name: e.title ?? '',
            date: e.releaseDate != null
                ? DateTime.parse(e.releaseDate!)
                : DateTime.now(),
            imageUrl:
                'https://image.tmdb.org/t/p/w220_and_h330_face${e.posterPath ?? ''}',
            rate: ((e.voteAverage ?? 0) * 10).round()))
        .toList();
  }
}
