import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:test_app/feature/home/provider/home_provider.dart';
import 'package:test_app/feature/home/state/home_picker_state.dart';
import 'package:test_app/shared/app_enum.dart';

part 'home_picker_provider.g.dart';

//Generated by @riverpod
// final homePickerNotifierProvider =
//     NotifierProvider<HomePickerNotifier, HomePickerState>(HomePickerNotifier.new);

@riverpod
class HomePickerNotifier extends _$HomePickerNotifier {
  @override
  HomePickerState build() {
    var initialTab = MovieType.popular;
    ref.read(homeNotifierProvider.notifier).reloadPage(initialTab);
    return HomePickerState(type: initialTab);
  }

  void pick(MovieType type) {
    if (state.type == type) return;

    state = state.copyWith(type: type);
    final mapState = ref.read(homeNotifierProvider).mapState;

    if (mapState[type]!.movies.isEmpty) {
      ref.read(homeNotifierProvider.notifier).reloadPage(type);
    }
  }
}
