import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:test_app/feature/home/repository/movie_repository.dart';
import 'package:test_app/feature/home/state/movie_state.dart';

part 'movie_provider.g.dart';

//Generated by @riverpod
// final movieNotifierProvider = NotifierProvider<MovieNotifier, MovieState>(() {
//   return MovieNotifier();
// });
@riverpod
class MovieNotifier extends _$MovieNotifier {
  late final MovieRepository _repository = ref.read(movieRepoProvider);

  @override
  MovieState build() {
    return const MovieState.loading();
  }
}
